apiVersion: v1
kind: Secret
metadata:
name: namespace-secret
type: Opaque
data:
# This is azure service bus namespace connection string
connection: << Your Service Bus Connection String Base64 encoded >>